eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/

server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
      host: localhost
      port: 5672
      username: zyy
      password: 123456
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service