eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/
server:
  port: 8902
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
        host: localhost
        port: 5672
        username: zyy
        password: 123456
  sleuth:
    sampler:
      percentage: 1.0